name: Fetch RSS Feeds
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # FIX: Use 'npm install' to resolve dependency mismatches in CI
      - name: Install dependencies
        run: npm install
      - name: Create Firebase Service Account Key
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: echo "$FIREBASE_KEY" > serviceAccountKey.json
      - name: Run feed fetch script
        run: node scripts/fetch-feeds.js
